TYPO3:
  Form:
    supertypeResolver:
      hiddenProperties: []
    Presets:
      Default:
        ########### DEFAULT ###########
        formElementTypes:

          ### BASE ELEMENTS ###

          # NAMING: base class for everything is RENDERABLE
          'TYPO3.Form:Base':
            renderingOptions:
              templatePathPattern: 'resource://{@package}/Private/Form/{@type}.html'
              partialPathPattern: 'resource://{@package}/Private/Form/Partials/{@type}.html'
              layoutPathPattern: 'resource://{@package}/Private/Form/Layout/{@type}.html'

          'TYPO3.Form:Form':
            superTypes: ['TYPO3.Form:Base']
            rendererClassName: 'TYPO3\Form\Core\Renderer\FluidFormRenderer'
            renderingOptions:
              renderableNameInTemplate: 'form'

          'TYPO3.Form:Page':
            superTypes: ['TYPO3.Form:Base']
            implementationClassName: 'TYPO3\Form\Core\Model\Page'
            renderingOptions:
              renderableNameInTemplate: 'page'

          'TYPO3.Form:Section':
            superTypes: ['TYPO3.Form:FormElement']
            implementationClassName: 'TYPO3\Form\FormElements\Section'
            renderingOptions:
              renderableNameInTemplate: 'section'

          'TYPO3.Form:FormElement':
            superTypes: ['TYPO3.Form:Base']
            implementationClassName: 'TYPO3\Form\FormElements\GenericFormElement'
            renderingOptions:
              renderableNameInTemplate: 'element'



          ### FORM ELEMENTS: Basics ###
          'TYPO3.Form:TextMixin': []
          'TYPO3.Form:Textarea':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:TextMixin']
          'TYPO3.Form:Textfield':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:TextMixin']
          'TYPO3.Form:Checkbox':
            superTypes: ['TYPO3.Form:FormElement']
          'TYPO3.Form:Date':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:TextMixin']
          'TYPO3.Form:ImageUpload':
            superTypes: ['TYPO3.Form:FormElement']
            implementationClassName: 'TYPO3\Form\FormElements\ImageUpload'
#            processingRule:
#              mapping:
#                targetType: '\TYPO3\Media\Domain\Model\Image'
            properties:
              allowedExtensions: ['jpg', 'jpeg', 'png', 'gif', 'bmp']

          ### FORM ELEMENTS: Single / Multi Select ###
          'TYPO3.Form:SelectionMixin': []
          'TYPO3.Form:SingleSelectionMixin':
            superTypes: ['TYPO3.Form:SelectionMixin']
          'TYPO3.Form:MultiSelectionMixin':
            superTypes: ['TYPO3.Form:SelectionMixin']

          'TYPO3.Form:Checkboxes':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:MultiSelectionMixin']
          'TYPO3.Form:Radiobuttons':
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:SingleSelectionMixin']
#            processingRule:
#              mapping:
#                availableOptions:
#                  dateFormat:
##                    type: string // boolean // .... # for graphical UI
##                    label: '....' # for graphical UI
#                    converterOptionName: 'TYPO3\FLOW3\Property\TypeConverter\DateTimeConverter::format'
#                targetType: '\DateTime'
#                options:
#                  dateFormat: 'Y-m-d'
          'TYPO3.Form:Select':
            # TODO: We need to split this into single and multiple select
            superTypes: ['TYPO3.Form:FormElement', 'TYPO3.Form:SelectionMixin']

           ### FINISHERS ###
        finisherTypes:
          'TYPO3.Form:Redirect':
            implementationClassName: 'TYPO3\Form\Finishers\RedirectFinisher'
            availableOptions:
              sender:
                type: 'string'

        ########### CUSTOM PRESETS ###########
#      SomePresetName:
#        parentPreset: 'Default'
#        formElementTypes:
#          'TYPO3.Form:Base':
#            renderingOptions:
#              templatePathPattern: 'resource://TYPO3.SomePackage/Private/Form/{@type}.html'