
TYPO3:
  Form:
    yamlPersistenceManager:
      savePath: '%FLOW_PATH_DATA%Forms/'
    supertypeResolver:
      hiddenProperties: {  }
    presets:
      default:
        title: Default
        stylesheets: {  }
        javaScripts: {  }
        formElementTypes:
          'TYPO3.Form:Base':
            renderingOptions:
              templatePathPattern: 'resource://{@package}/Private/Form/{@type}.html'
              partialPathPattern: 'resource://{@package}/Private/Form/Partials/{@type}.html'
              layoutPathPattern: 'resource://{@package}/Private/Form/Layouts/{@type}.html'
              skipUnknownElements: false
              translationPackage: TYPO3.Form
              validationErrorTranslationPackage: Neos.Flow
          'TYPO3.Form:Form':
            superTypes:
              'TYPO3.Form:Base': true
            rendererClassName: TYPO3\Form\Core\Renderer\FluidFormRenderer
            renderingOptions:
              renderableNameInTemplate: form
          'TYPO3.Form:RemovableMixin': {  }
          'TYPO3.Form:ReadOnlyFormElement':
            superTypes:
              'TYPO3.Form:Base': true
              'TYPO3.Form:RemovableMixin': true
            implementationClassName: TYPO3\Form\FormElements\GenericFormElement
            renderingOptions:
              renderableNameInTemplate: element
          'TYPO3.Form:FormElement':
            superTypes:
              'TYPO3.Form:Base': true
              'TYPO3.Form:RemovableMixin': true
            implementationClassName: TYPO3\Form\FormElements\GenericFormElement
            properties:
              containerClassAttribute: input
              elementClassAttribute: ''
              elementErrorClassAttribute: error
            renderingOptions:
              renderableNameInTemplate: element
          'TYPO3.Form:Page':
            superTypes:
              'TYPO3.Form:Base': true
              'TYPO3.Form:RemovableMixin': true
            implementationClassName: TYPO3\Form\Core\Model\Page
            renderingOptions:
              renderableNameInTemplate: page
          'TYPO3.Form:PreviewPage':
            superTypes:
              'TYPO3.Form:Page': true
          'TYPO3.Form:Section':
            superTypes:
              'TYPO3.Form:FormElement': true
            implementationClassName: TYPO3\Form\FormElements\Section
            renderingOptions:
              renderableNameInTemplate: section
          'TYPO3.Form:TextMixin': {  }
          'TYPO3.Form:SingleLineText':
            superTypes:
              'TYPO3.Form:FormElement': true
              'TYPO3.Form:TextMixin': true
          'TYPO3.Form:Password':
            superTypes:
              'TYPO3.Form:FormElement': true
              'TYPO3.Form:TextMixin': true
          'TYPO3.Form:PasswordWithConfirmation':
            superTypes:
              'TYPO3.Form:Password': true
            implementationClassName: TYPO3\Form\FormElements\PasswordWithConfirmation
            properties:
              elementClassAttribute: input-medium
              confirmationLabel: Confirmation
              confirmationClassAttribute: input-medium
          'TYPO3.Form:MultiLineText':
            superTypes:
              'TYPO3.Form:FormElement': true
              'TYPO3.Form:TextMixin': true
            properties:
              elementClassAttribute: xxlarge
          'TYPO3.Form:SelectionMixin': {  }
          'TYPO3.Form:SingleSelectionMixin':
            superTypes:
              'TYPO3.Form:SelectionMixin': true
          'TYPO3.Form:MultiSelectionMixin':
            superTypes:
              'TYPO3.Form:SelectionMixin': true
          'TYPO3.Form:Checkbox':
            superTypes:
              'TYPO3.Form:FormElement': true
            properties:
              elementClassAttribute: add-on
              value: 1
          'TYPO3.Form:MultipleSelectCheckboxes':
            superTypes:
              'TYPO3.Form:FormElement': true
              'TYPO3.Form:MultiSelectionMixin': true
          'TYPO3.Form:MultipleSelectDropdown':
            superTypes:
              'TYPO3.Form:FormElement': true
              'TYPO3.Form:MultiSelectionMixin': true
            properties:
              elementClassAttribute: xlarge
          'TYPO3.Form:SingleSelectRadiobuttons':
            superTypes:
              'TYPO3.Form:FormElement': true
              'TYPO3.Form:SingleSelectionMixin': true
            properties:
              elementClassAttribute: xlarge
          'TYPO3.Form:SingleSelectDropdown':
            superTypes:
              'TYPO3.Form:FormElement': true
              'TYPO3.Form:SingleSelectionMixin': true
          'TYPO3.Form:DatePicker':
            superTypes:
              'TYPO3.Form:FormElement': true
            implementationClassName: TYPO3\Form\FormElements\DatePicker
            properties:
              elementClassAttribute: small
              timeSelectorClassAttribute: mini
              dateFormat: Y-m-d
              enableDatePicker: true
              displayTimeSelector: false
          'TYPO3.Form:FileUpload':
            superTypes:
              'TYPO3.Form:FormElement': true
            implementationClassName: TYPO3\Form\FormElements\FileUpload
            properties:
              allowedExtensions:
                - pdf
                - doc
          'TYPO3.Form:ImageUpload':
            superTypes:
              'TYPO3.Form:FormElement': true
            implementationClassName: TYPO3\Form\FormElements\ImageUpload
            properties:
              allowedTypes:
                - jpeg
                - png
                - bmp
          'TYPO3.Form:StaticText':
            superTypes:
              'TYPO3.Form:ReadOnlyFormElement': true
            properties:
              text: ''
          'TYPO3.Form:HiddenField':
            superTypes:
              'TYPO3.Form:FormElement': true
        finisherPresets:
          'TYPO3.Form:Closure':
            implementationClassName: TYPO3\Form\Finishers\ClosureFinisher
            options: {  }
          'TYPO3.Form:Confirmation':
            implementationClassName: TYPO3\Form\Finishers\ConfirmationFinisher
            options: {  }
          'TYPO3.Form:Email':
            implementationClassName: TYPO3\Form\Finishers\EmailFinisher
            options: {  }
          'TYPO3.Form:FlashMessage':
            implementationClassName: TYPO3\Form\Finishers\FlashMessageFinisher
            options: {  }
          'TYPO3.Form:Redirect':
            implementationClassName: TYPO3\Form\Finishers\RedirectFinisher
            options: {  }
        validatorPresets:
          'Neos.Flow:NotEmpty':
            implementationClassName: Neos\Flow\Validation\Validator\NotEmptyValidator
          'Neos.Flow:DateTimeRange':
            implementationClassName: Neos\Flow\Validation\Validator\DateTimeRangeValidator
          'Neos.Flow:Alphanumeric':
            implementationClassName: Neos\Flow\Validation\Validator\AlphanumericValidator
          'Neos.Flow:Text':
            implementationClassName: Neos\Flow\Validation\Validator\TextValidator
          'Neos.Flow:StringLength':
            implementationClassName: Neos\Flow\Validation\Validator\StringLengthValidator
          'Neos.Flow:EmailAddress':
            implementationClassName: Neos\Flow\Validation\Validator\EmailAddressValidator
          'Neos.Flow:Integer':
            implementationClassName: Neos\Flow\Validation\Validator\IntegerValidator
          'Neos.Flow:Float':
            implementationClassName: Neos\Flow\Validation\Validator\FloatValidator
          'Neos.Flow:NumberRange':
            implementationClassName: Neos\Flow\Validation\Validator\NumberRangeValidator
          'Neos.Flow:RegularExpression':
            implementationClassName: Neos\Flow\Validation\Validator\RegularExpressionValidator
          'Neos.Flow:Count':
            implementationClassName: Neos\Flow\Validation\Validator\CountValidator
  DocTools:
    bundles:
      Form:
        documentationRootPath: '%FLOW_PATH_PACKAGES%Application/TYPO3.Form/Documentation/Guide/source'
        renderedDocumentationRootPath: '%FLOW_PATH_DATA%Temporary/Documentation/Form'
        configurationRootPath: '%FLOW_PATH_PACKAGES%Application/TYPO3.Form/Documentation/Guide/source'
        imageRootPath: '%FLOW_PATH_PACKAGES%Application/TYPO3.Form/Documentation/Guide/Images/'
